### ISSUE TITLE
Support auto-resolving of alerts

### ISSUE THREAD

**Issue by SerialVelocity** [xmatters/xm-labs-prometheus#6]
Currently, enabling the `send_resolved` flag just creates a new alert with `RESOLVED` in the title. It would be nice if this resolved an existing alert.

**Comment by xMTinkerer** [comment]
Sweet, good catch. We'll start working on a new release in the next week or so. I'll make sure we capture this.

**Comment by xMTinkerer** [comment]
@SerialVelocity, we're working on updating this integration but I need some clarification on what you want to see. 
When alertmanager sends the resolved alert to xMatters, you just want to terminate the _events_ in xMatters, right? I don't see an API in prometheus or alertmanager to resolve the Alert, but we're adding a Create and Delete Silence that should help stop the madness.

**Comment by SerialVelocity** [comment]
Yes please. It seems like alerts can resolve themselves in three ways (`jq` syntax):
 - With the overall status being "resolved" (`.status == "resolved"`)
 - With a single alert's status being "resolved" (`.alerts[] | select(.status == "resolved")`)
 - With a single alert's `endsAt` time being in the past and not `0001-01-01T00:00:00Z` (not sure what happens if the system has a timezone) (`.alerts[] | select(.endsAt" != "0001-01-01T00:00:00Z" and .endsAt <= (now | strftime("%Y-%m-%dT%H:%M:%S%z") | sub("\\+0000$"; "Z")))`)

You can silence alerts in AlertManager but I don't think an event is sent out when that happens.

**Comment by xMTinkerer** [comment]
Ok, so we did some digging. I also need to clarify. Alertmanager deals in Alerts, in xMatters we have "events" that deal with notifying people and escalations. So I think your question is mostly around when to terminate the event in xMatters (and thus stop escalations and further notifications for that event). 
So, in that vein, we should terminate the event in xMatters if **any** of the following are true, right?
* `.status == "resolved"`
* `.alerts[] | select(.status == "resolved")`. i.e. one of the alerts in the group gets resolved
* `.alerts[] | select(.endsAt" != "0001-01-01T00:00:00Z" and .endsAt <= (now | strftime("%Y-%m-%dT%H:%M:%S%z") | sub("\\+0000$"; "Z")))`

In our poking around, we found that the endsAt value is only populated when the alert is resolved. Is there another way to set this? We found some documentation [here](https://prometheus.io/docs/alerting/clients/) that talks about submitting alerts via API instead of through prometheus. 

It seems the silence will silence the alert, but when it gets resolved alertmanager sends the resolved after the silence expires or is deleted.

**Comment by SerialVelocity** [comment]
You are correct. I want the event to be terminated.

And yes, if *any* of those conditions are true.

I don't know if it is possible to populate the `endsAt` value manually. Maybe to be safe you should make sure it is past the current time?

**Comment by lmtyler** [comment]
Any status updates on this?  The resolved page out is painful at 2am ;P

**Comment by xMTinkerer** [comment]
Oh man. Sorry guys, yes, this has been resolved. You'll need to import the new workflow zip file and update your urls and such. When Alertmanager sends the "resolved" signal, the events are terminated in xMatters.
